smsgatewayApp/urls.py
from django.urls import path
from smsgatewayApp import views
app_name='smsgatewayApp'
urlpatterns = [
  
    path('',views.smssendAPI,name='smssendAPI'),
    path('smsdisplay/', views.smsDisplay, name='smsdisplay'),
    path('statusUpdate/',views.statusUpdate,name='statusUpdate'),


]

smsgatewayProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('smsgatewayApp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                       document_root=settings.STATIC_ROOT  )
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

smsgatewayApp/models.py
from django.db import models

# Create your models here.
class SMS(models.Model):
    messageid = models.CharField(max_length=250)
    message = models.CharField(max_length=250)
    phone=models.CharField(max_length=250)
    def __str__(self):
        return self.phone
class StatusLog(models.Model):
    messageid = models.CharField(max_length=250)
    status = models.CharField(max_length=250)
    updated= models.CharField(max_length=250)
    def __str__(self):
        return self.messageid

smsgatewayApp/views.py
from __future__ import absolute_import,unicode_literals
import requests
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
import json
from import_export.formats.base_formats import JSON
from .models import SMS,StatusLog



@csrf_exempt
# Create your views here.
def smssendAPI(request):
    if request.method == 'POST':
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        messageid = body['id']
        number = body['number']
        message = body['message']
        SMSDb = SMS()
        SMSDb.messageid = messageid
        SMSDb.phone = number
        SMSDb.message = message
        SMSDb.save()
    return redirect('/smssendAPI')


def smsDisplay(request):
    sms_db = SMS.objects.all()
    return render(request, 'displayMessage.html', {'smsdb': sms_db})


def statusUpdate(request):
        print("called-----------")
        id= request.GET.get('id')
        message=request.GET.get('message')
        status1=request.GET.get('status')
        print("id:",id)
        print("message:",message)
        print("status:",status1)
        if ((status1 != "Choose Delivery status")  and (id != "")):
            if(StatusLog.objects.filter(messageid=id).exists()):
                        StatusLog.objects.filter(messageid=id).update(status=status1,updated="false")
                        messages.info(request,"Status Updated")
            else:
                        statuslog = StatusLog()
                        statuslog.messageid =id
                        statuslog.status =status1
                        statuslog.updated="false"
                        statuslog.save()
           
        return redirect('smsdisplay/')

# @shared_task
# def schedule1():
#     sms_status = StatusLog.objects.filter(updated="false")
#     print(list(sms_status.values('messageid','status')))
#     payload = {'status':sms_status}
#     headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
#     url = "http://127.0.0.1:8000/smsDeliveryStatus"
#     # requests.post(url, data=json.dumps(payload), headers=headers)
#     StatusLog.objects.filter(updated="false").update(updated="true")

   
  
   

templates/displayMessage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Table 03</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'table-03/css/style.css'%}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Message</h2>
				</div>
			</div>
			{% for message in messages %}

				<div class="alert alert-success">
					<a class="close" href="#" data-dismiss="alert">×</a>
					<p> {{ message }}</p>

				</div>
			{% endfor %}
			<form method="POST" action="" data-center-url="{% url 'smsgatewayApp:statusUpdate' %}" id="update">
				  {%csrf_token%}
			<div class="row">
				<div class="col-md-12">
					<h4 class="text-center mb-4"></h4>
					<div class="table-wrap">
						<table class="table">
					    <thead class="thead-primary">
					      <tr>
					        <th>Phone Number</th>

					        <th>Message</th>
					        <th>Status</th>
							  <th>Update</th>
							    <th style="display:none;">Message Id</th>


					      </tr>
					    </thead>
					    <tbody>

						{% for i in smsdb %}
					      <tr>

					          <td name="phone" class="nr">{{i.phone}}</td>
							  <td name="message1">{{i.message}}</td>
							  <td name="status2">
								<select name="status1" id="status1">
									 <option value="default" disabled selected hidden>Choose Delivery status</option>
									 <option value="sent">Sent</option>
									 <option value="Druck">Fail</option>
									 <option value="Zahl">Delivered</option>
								</select>
							  </td>
							  <td name="button1"><a href="" class="btn btn-primary grabId"  id="update1">Update</a></td>

							  <td name="id1" style="display:none;">{{i.messageid}}</td>

					      </tr>
						{% endfor %}

					    </tbody>
					  </table>
					</div>
				</div>
			</div>
			</form>
		</div>
	</section>

	<script src="{% static 'table-03/js/jquery.min.js' %}"></script>
  <script src="{% static 'table-03/js/popper.js' %}"></script>
  <script src="{% static 'table-03/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'table-03/js/main.js' %}"></script>

	</body>

<script>

var a=[]
var b
  $(".grabId").click(function() {
    var $row = $(this).closest("tr");    // Find the row
    var $tds = $row.find("td");
    $.each($tds, function() {
    	a.push($(this).text())
    	 });

 $other_dropdown = $row.find('#status1 :selected').text();
 b= $other_dropdown
alert((b));
var url = $("#update").attr("data-center-url");
 $.ajax({
         url: url,
         data: {
         'id': a[4],
         'message':a[1],
         'status':b

        }
        });
});

</script>
</html>